#!/bin/bash

source ./config/config
source ./script/functions

echo ""
for host in $hosts
do

	echo -n "正在${host}安裝套件wget、openssh-clients、bc ..... " | tee -a deploy.log
	remote_cmd "$host" "rpm -q wget openssh-clients bc > /dev/null"
	if [ $? -ne 0 ]; then
		remote_cmd "$host" "yum install -y wget openssh-clients bc --setopt=sslverify=false"
		check_status || exit 1
	else
		font_color -s
		echo "[ OK ]" >> deploy.log
	fi
done

echo ""
for host in $hosts
do

	echo -n "正在${host}安裝epel-release rpm ..... " | tee -a deploy.log
	remote_cmd "$host" "rpm -q epel-release > /dev/null"
	if [ $? -ne 0 ]; then

		remote_cmd "$host" "yum -y localinstall ${epel_el6} --setopt=sslverify=false"
		check_status || exit 1
	else
		font_color -s
		echo "[ OK ]" >> deploy.log
	fi
done

#echo ""
#for host in $hosts
#do
#	echo -n "正在${host}設定/etc/host檔 ..... " | tee -a deploy.log
#	remote_cmd "$host" "sed -i.bak '/::1/d' /etc/hosts"
#	check_status || exit 1
#done

echo ""
for host in $hosts
do
	echo -n "正在${host}清除YUM快取 ..... " | tee -a deploy.log
	remote_cmd "$host" "yum clean all > /dev/null"
	check_status

done
echo ""


if [ "$perf_tuning" == "yes" ]; then

	echo "#!/bin/bash" > tmp/tuning_info
	
	echo ""
	for host in $hosts
	do
		echo -n "正在${host}取得CPU資訊 ..... " | tee -a deploy.log
		cpu_info=${cpu_info}$(ssh -nq -p "$ssh_port" "$deploy_user"@"$host" cat /proc/cpuinfo | grep 'processor' | tail -n1 | awk '{ print $3 }')" "
		check_status || exit 1
	done
	
	echo -n "正在計算最小CPU Core ..... " | tee -a deploy.log
	for cc in $cpu_info
	do
		if [ ! "$min_core" ]; then
			min_core=$cc
		elif [ $cc -lt $min_core ]; then
			min_core=$cc
		fi	
	done
	cpu_core=$(expr ${min_core} + 1)
	echo "cpu_core=$cpu_core" >> tmp/tuning_info
	check_status || exit 1
	
	for host in $hosts
	do
		echo -n "正在${host}取得記憶體總容量 ..... " | tee -a deploy.log
		mem=${mem}$(ssh -nq -p "$ssh_port" "$deploy_user"@"$host" free -m | grep 'Mem' | awk '{ print $2 }')" "
		check_status || exit 1
	done
	
	echo -n "正在計算最小記憶體總容量 ..... " | tee -a deploy.log
	for mm in $mem
	do
		if [ ! "$total_mem" ]; then
			total_mem=$mm
		elif [ $mm -lt $total_mem ]; then
			total_mem=$mm
		fi
	done
	echo "total_mem=${total_mem}" >> tmp/tuning_info
	check_status || exit 1

	echo -n "正在計算記憶體可用容量 ..... " | tee -a deploy.log
	avail_mem=`echo "${total_mem} * 0.9" | bc | cut -d'.' -f1`
	avail_mem=`expr ${avail_mem} / 3`
	echo "avail_mem=${avail_mem}" >> tmp/tuning_info
	check_status || exit 1

	echo ""
	for host in $hosts
	do
	        echo -n "正在${host}取得根目錄可用容量 ..... " | tee -a deploy.log
	        disk_info=${disk_info}$(ssh -nq -p "$ssh_port" "$deploy_user"@"$host" df -m | grep -w '/' | awk '{ print $3 }' | head -n1)" "
	        check_status || exit 1
	done
	
	echo -n "正在計算根目錄最小可用容量 ..... " | tee -a deploy.log
	for d in $disk_info
	do
	        if [ ! "$disk_size" ]; then
	                disk_size=$d
	        elif [ $d -lt $disk_size ]; then
	                disk_size=$d
	        fi
	done
	
	echo "disk_size=$disk_size" >> tmp/tuning_info
	check_status || exit 1
fi

echo ""
