#!/bin/bash

source ./config/config
source ./script/functions


if [ -f ${HOME}/.ssh/id_rsa.pub ]; then
	read -p "檔案${HOME}/.ssh/id_rsa.pub已經存在，你要使用它嗎 (y/n)? " answer
	
	if [ "${answer}" != "y" ]; then
		rm -f ${HOME}/.ssh/id_rsa.pub 2>>deploy.log
		rm -f ${HOME}/.ssh/id_rsa 2>>deploy.log
		font_color --text "若不指定id_rsa檔案的存放位置請按Enter鍵" --color red
		ssh-keygen -t rsa -q -N ''
	fi
else
	font_color --text "若不指定id_rsa檔案的存放位置請按Enter鍵" --color red
	ssh-keygen -t rsa -q -N ''
fi


key=`cat ~/.ssh/id_rsa.pub 2>&1`

font_color --text "若出現'${USER}@IP's password:'時請輸入您的密碼" --color red

for host in $hosts
do
	echo "正在複製${HOME}/.ssh/id_rsa.pub到${host} ..... "
	ssh -t -p ${ssh_port} ${USER}@${host} "mkdir -p ${HOME}/.ssh && echo ${key} >> ${HOME}/.ssh/authorized_keys && chmod 644 ${HOME}/.ssh/authorized_keys && chmod 700  ${HOME}/.ssh && restorecon -R ${HOME}/.ssh" 2>>deploy.log
	check_status || exit 1
done
